# Nome do Workflow
name: CI de Testes Python

# Gatilho: rodar em Pull Requests para a branch main
on:
  pull_request:
    branches: [ main ]

jobs:
  test-job:
    name: Executar Testes Unitários
    runs-on: ubuntu-latest
    steps:
      - name: 1. Checkout do código
        uses: actions/checkout@v4

      - name: 2. Configurar Python 3.10
        uses: actions/setup-python@v4
        with:
          python-version: '3.10'

      - name: 3. Instalar dependências
        run: |
          python -m pip install --upgrade pip
          pip install pytest

      - name: 4. Rodar os testes
        run: |
          export PYTHONPATH=.
          pytest